# the first step is always the same: import all necessary components:
import smtplib, ssl
from socket import gaierror
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# now you can play with your code. Let’s define the SMTP server separately here:
port = 2525 
smtp_server = "smtp.mailtrap.io"
login = "0eba20a85d55cd" # paste your login generated by Mailtrap
password = "b7a47dd03f13f3" # paste your password generated by Mailtrap

# specify the sender’s and receiver’s email addresses
sender = "donotreply@ICMS.com"
receiver = "joyce36@hku.com"
# type your message: use two newlines (\n) to separate the subject from the message body, and use 'f' to  automatically insert variables in the text
message = MIMEMultipart("alternative")
message["Subject"] = "Hi"
message["From"] = sender
message["To"] = receiver

content = """\
This is my first message with Python."""

part1 = MIMEText(content, "plain")
message.attach(part1)
try:
    #send your message with credentials specified above
    with smtplib.SMTP(smtp_server, port) as server:
        server.login(login, password)
        server.sendmail(sender, receiver, message.as_string())

    # tell the script to report if your message was sent or which errors need to be fixed 
    print('Sent')
except (gaierror, ConnectionRefusedError):
    print('Failed to connect to the server. Bad connection settings?')
except smtplib.SMTPServerDisconnected:
    print('Failed to connect to the server. Wrong user/password?')
except smtplib.SMTPException as e:
    print('SMTP error occurred: ' + str(e))
